version: '3.8'
services:
  app:
    build:
      context: ./
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

volumes:
  node_modules: